name: Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache npm modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build and run the Docker container
      run: |
        docker build .devcontainer -t my-application
        docker run --name my-app-container -d my-application tail -f /dev/null

    - name: Copy project files into the Docker container
      run: docker cp . my-app-container:/app

    - name: Install dependencies and build the project
      run: |
        docker exec my-app-container bash -c "cd /app/book && npm install"
        docker exec my-app-container bash -c "cd /app/book && node ./scripts/head2toc.js && npm run build:sass && vivliostyle build --no-sandbox && node ./scripts/cover.js"

    - name: Copy the output PDF from the Docker container
      run: docker cp my-app-container:/app/book/output.pdf ./output.pdf

    - name: Upload output.pdf as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-pdf
        path: ./output.pdf
